# LLM-based Relevance Validation

This notebook evaluates the relevance of original and synthetic queries
to their corresponding documents using an independent OpenAI language model.

The relevance judge is not informed whether a query is original or synthetic.
It only receives the query and its corresponding document.

Relevance is assessed on a four-point scale from 0 (irrelevant) to
3 (perfectly relevant).

## Imports

In [ ]:
import json
import pandas as pd
from google.colab import userdata
from openai import OpenAI

## API configuration

In [ ]:
api_key = userdata.get("OPENAI_API_KEY").strip()

client = OpenAI(api_key=api_key)

MODEL = "gpt-5.6-luna"

## Load datasets

In [ ]:
news = pd.read_csv("news_full_augmented.csv")
tenders = pd.read_csv("tenders_full_augmented.csv")
abstracts = pd.read_csv("abstracts_full_augmented_clean.csv")

In [ ]:
news.head()

,query_id,corpus_id,score,original_query,document_text,synthetic_query,assigned_task_type
0,7834,7834,1,Verzetsman na 66 jaar begraven,Vandaag wordt in het Noord-Hollandse Heiloo ve...,Hoe werd een Nederlandse oorlogsslachtoffer na...,Task_1
1,124788,124788,1,"Als er kritiek is op de koning, gaat het altij...",Koning Willem-Alexander zit ruim duizend dagen...,Waarom is er kritiek op de financiële uitgaven...,Task_2
2,202109,202109,1,Steeds meer elektrische scooters op de weg,Steeds meer mensen kiezen voor een elektrische...,Klopt de bewering dat elektrische scooters ste...,Task_3
3,93877,93877,1,Militair met drugs gepakt op Curaçao,Op Curaçao is een Nederlandse militair van 25...,Wat is er bekend over de arrestatie van een mi...,Task_1
4,20941,20941,1,Deense grenscontroles vanaf dinsdag,Het Deense parlement heeft ingestemd met het o...,Uitleg over herinvoering grenscontroles en de ...,Task_2

In [ ]:
print(len(news))
print(len(tenders))
print(len(abstracts))

1000
1000
1000

## Define relevance scale

In [ ]:
RELEVANCE_SCALE = """
0 = Irrelevant
The document does not contain information that addresses the information
need expressed by the query.

1 = Related
The document is topically related to the query, but does not provide
sufficient information to satisfy the information need.

2 = Highly relevant
The document provides substantial information that addresses the
information need expressed by the query.

3 = Perfectly relevant
The document directly and comprehensively satisfies the information
need expressed by the query.
"""

## Define final judge prompt

In [ ]:
SYSTEM_PROMPT = f"""
You are an information retrieval relevance assessor.

Your task is to judge how relevant a document is to a search query.

Evaluate ONLY whether the document contains information that addresses
the information need expressed by the query.

Do NOT judge:
- whether the query is well-written;
- whether the query is grammatically correct;
- whether the query sounds natural;
- whether the query was written by a human or generated by an AI system.

Do not assume that the query is relevant simply because it is paired
with the document.

Use the following relevance scale:

{RELEVANCE_SCALE}

Provide a brief explanation for your judgment.

The output must follow the specified JSON schema.
"""

## Define structured output scheme

In [ ]:
RELEVANCE_SCHEMA = {
    "type": "object",
    "properties": {
        "relevance_score": {
            "type": "integer",
            "enum": [0, 1, 2, 3]
        },
        "reason": {
            "type": "string"
        }
    },
    "required": ["relevance_score", "reason"],
    "additionalProperties": False
}

## Define judge_relevance()

In [ ]:


def judge_relevance(query, document):
    response = client.responses.create(
        model=MODEL,
        instructions=SYSTEM_PROMPT,
        input=f"""
DOCUMENT:
{document}

QUERY:
{query}
""",
        text={
            "format": {
                "type": "json_schema",
                "name": "relevance_judgment",
                "description": "Relevance judgment for a query-document pair.",
                "schema": RELEVANCE_SCHEMA,
                "strict": True
            }
        }
    )

    result = json.loads(response.output_text)

    return {
        "relevance_score": result["relevance_score"],
        "reason": result["reason"]
    }

## Prepare final evaluation data

In [ ]:
news["dataset"] = "News"
tenders["dataset"] = "Tenders"
abstracts["dataset"] = "Abstracts"

relevance_df = pd.concat(
    [news, tenders, abstracts],
    ignore_index=True
)

## Check dataset sizes

In [ ]:
relevance_df.head()

,query_id,corpus_id,score,original_query,document_text,synthetic_query,assigned_task_type,dataset
0,7834,7834,1,Verzetsman na 66 jaar begraven,Vandaag wordt in het Noord-Hollandse Heiloo ve...,Hoe werd een Nederlandse oorlogsslachtoffer na...,Task_1,News
1,124788,124788,1,"Als er kritiek is op de koning, gaat het altij...",Koning Willem-Alexander zit ruim duizend dagen...,Waarom is er kritiek op de financiële uitgaven...,Task_2,News
2,202109,202109,1,Steeds meer elektrische scooters op de weg,Steeds meer mensen kiezen voor een elektrische...,Klopt de bewering dat elektrische scooters ste...,Task_3,News
3,93877,93877,1,Militair met drugs gepakt op Curaçao,Op Curaçao is een Nederlandse militair van 25...,Wat is er bekend over de arrestatie van een mi...,Task_1,News
4,20941,20941,1,Deense grenscontroles vanaf dinsdag,Het Deense parlement heeft ingestemd met het o...,Uitleg over herinvoering grenscontroles en de ...,Task_2,News

In [ ]:
len(relevance_df)

3000

In [ ]:
relevance_df.columns

Index(['query_id', 'corpus_id', 'score', 'original_query', 'document_text',
       'synthetic_query', 'assigned_task_type', 'dataset'],
      dtype='object')

## Run relevance labelling with checkpointing

In [ ]:
import os
import pandas as pd
import time

OUTPUT_PATH = "relevance_labels_final.csv"

results = []

In [ ]:
def label_row(row, query_type):

    if query_type == "original":
        query = row["original_query"]
    elif query_type == "synthetic":
        query = row["synthetic_query"]
    else:
        raise ValueError(f"Unknown query type: {query_type}")

    judgment = judge_relevance(
        query=query,
        document=row["document_text"]
    )

    return {
        "query_id": row["query_id"],
        "corpus_id": row["corpus_id"],
        "dataset": row["dataset"],
        "query_type": query_type,
        "assigned_task_type": row["assigned_task_type"],
        "query": query,
        "relevance_score": judgment["relevance_score"],
        "reason": judgment["reason"]
    }

In [ ]:
cases = []

for _, row in relevance_df.iterrows():

    cases.append((row, "original"))
    cases.append((row, "synthetic"))

print("Total cases:", len(cases))

Total cases: 6000

In [ ]:
CHECKPOINT_PATH = "relevance_labels_checkpoint.csv"

if os.path.exists(CHECKPOINT_PATH):
    results_df = pd.read_csv(CHECKPOINT_PATH)

    completed = set(
        zip(
            results_df["query_id"],
            results_df["query_type"]
        )
    )

    print(f"Existing labels: {len(results_df)}")
else:
    results_df = pd.DataFrame()
    completed = set()

    print("Starting from zero.")

Starting from zero.

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
CHECKPOINT_PATH = (
    "/content/drive/MyDrive/"
    "relevance_labels_checkpoint.csv"
)

In [ ]:
for i, (row, query_type) in enumerate(cases, start=1):

    key = (row["query_id"], query_type)

    # Skip if already completed
    if key in completed:
        continue

    try:
        result = label_row(row, query_type)

        results_df = pd.concat(
            [
                results_df,
                pd.DataFrame([result])
            ],
            ignore_index=True
        )

        # Save after EVERY label
        results_df.to_csv(
            CHECKPOINT_PATH,
            index=False
        )

        print(
            f"[{i}/{len(cases)}] "
            f"{row['dataset']} | "
            f"{query_type} | "
            f"{row['query_id']} | "
            f"Score: {result['relevance_score']}"
        )

    except Exception as e:
        print(
            f"ERROR at {i}/{len(cases)} "
            f"| {row['dataset']} "
            f"| {row['query_id']} "
            f"| {query_type}"
        )
        print(e)

        # Stop so the error can be inspected
        raise

Streaminguitvoer ingekort tot de laatste 5000 regels.
[1001/6000] News | original | 194567 | Score: 3
[1002/6000] News | synthetic | 194567 | Score: 3
[1003/6000] News | original | 25427 | Score: 3
[1004/6000] News | synthetic | 25427 | Score: 3
[1005/6000] News | original | 93453 | Score: 3
[1006/6000] News | synthetic | 93453 | Score: 3
[1007/6000] News | original | 119274 | Score: 3
[1008/6000] News | synthetic | 119274 | Score: 2
[1009/6000] News | original | 37162 | Score: 3
[1010/6000] News | synthetic | 37162 | Score: 3
[1011/6000] News | original | 182302 | Score: 3
[1012/6000] News | synthetic | 182302 | Score: 3
[1013/6000] News | original | 156831 | Score: 3
[1014/6000] News | synthetic | 156831 | Score: 2
[1015/6000] News | original | 151511 | Score: 3
[1016/6000] News | synthetic | 151511 | Score: 3
[1017/6000] News | original | 107218 | Score: 3
[1018/6000] News | synthetic | 107218 | Score: 3
[1019/6000] News | original | 153856 | Score: 3
[1020/6000] News | synthetic | 153856 | Score: 3
[1021/6000] News | original | 237242 | Score: 3
[1022/6000] News | synthetic | 237242 | Score: 3
[1023/6000] News | original | 60877 | Score: 3
[1024/6000] News | synthetic | 60877 | Score: 3
[1025/6000] News | original | 2439 | Score: 3
[1026/6000] News | synthetic | 2439 | Score: 3
[1027/6000] News | original | 1267 | Score: 3
[1028/6000] News | synthetic | 1267 | Score: 3
[1029/6000] News | original | 154691 | Score: 3
[1030/6000] News | synthetic | 154691 | Score: 3
[1031/6000] News | original | 166678 | Score: 3
[1032/6000] News | synthetic | 166678 | Score: 3
[1033/6000] News | original | 167876 | Score: 3
[1034/6000] News | synthetic | 167876 | Score: 3
[1035/6000] News | original | 53684 | Score: 3
[1036/6000] News | synthetic | 53684 | Score: 3
[1037/6000] News | original | 89909 | Score: 3
[1038/6000] News | synthetic | 89909 | Score: 3
[1039/6000] News | original | 233491 | Score: 3
[1040/6000] News | synthetic | 233491 | Score: 3
[1041/6000] News | original | 6702 | Score: 3
[1042/6000] News | synthetic | 6702 | Score: 3
[1043/6000] News | original | 88826 | Score: 3
[1044/6000] News | synthetic | 88826 | Score: 3
[1045/6000] News | original | 83845 | Score: 3
[1046/6000] News | synthetic | 83845 | Score: 3
[1047/6000] News | original | 110338 | Score: 3
[1048/6000] News | synthetic | 110338 | Score: 3
[1049/6000] News | original | 82147 | Score: 3
[1050/6000] News | synthetic | 82147 | Score: 3
[1051/6000] News | original | 97293 | Score: 3
[1052/6000] News | synthetic | 97293 | Score: 3
[1053/6000] News | original | 219279 | Score: 3
[1054/6000] News | synthetic | 219279 | Score: 3
[1055/6000] News | original | 114323 | Score: 3
[1056/6000] News | synthetic | 114323 | Score: 2
[1057/6000] News | original | 18003 | Score: 3
[1058/6000] News | synthetic | 18003 | Score: 3
[1059/6000] News | original | 136356 | Score: 3
[1060/6000] News | synthetic | 136356 | Score: 3
[1061/6000] News | original | 213230 | Score: 3
[1062/6000] News | synthetic | 213230 | Score: 3
[1063/6000] News | original | 125385 | Score: 3
[1064/6000] News | synthetic | 125385 | Score: 3
[1065/6000] News | original | 197989 | Score: 3
[1066/6000] News | synthetic | 197989 | Score: 3
[1067/6000] News | original | 30091 | Score: 3
[1068/6000] News | synthetic | 30091 | Score: 3
[1069/6000] News | original | 40452 | Score: 3
[1070/6000] News | synthetic | 40452 | Score: 3
[1071/6000] News | original | 30321 | Score: 3
[1072/6000] News | synthetic | 30321 | Score: 3
[1073/6000] News | original | 251300 | Score: 3
[1074/6000] News | synthetic | 251300 | Score: 3
[1075/6000] News | original | 201543 | Score: 3
[1076/6000] News | synthetic | 201543 | Score: 3
[1077/6000] News | original | 119099 | Score: 3
[1078/6000] News | synthetic | 119099 | Score: 3
[1079/6000] News | original | 94633 | Score: 3
[1080/6000] News | synthetic | 94633 | Score: 3
[1081/6000] News | original | 92102 | Score: 3
[1082/6000] News | synthetic | 92102 | Score: 3
[1083/6000] News | original | 155461 | Score: 3
[1084/6000] News | synthetic | 155461 | Score: 3
[1085/6000] News | original | 223873 | Score: 3
[1086/6000] News | synthetic | 223873 | Score: 3
[1087/6000] News | original | 227167 | Score: 3
[1088/6000] News | synthetic | 227167 | Score: 3
[1089/6000] News | original | 163282 | Score: 3
[1090/6000] News | synthetic | 163282 | Score: 3
[1091/6000] News | original | 20434 | Score: 3
[1092/6000] News | synthetic | 20434 | Score: 3
[1093/6000] News | original | 28073 | Score: 3
[1094/6000] News | synthetic | 28073 | Score: 3
[1095/6000] News | original | 132221 | Score: 3
[1096/6000] News | synthetic | 132221 | Score: 3
[1097/6000] News | original | 73548 | Score: 3
[1098/6000] News | synthetic | 73548 | Score: 3
[1099/6000] News | original | 68807 | Score: 3
[1100/6000] News | synthetic | 68807 | Score: 3
[1101/6000] News | original | 118948 | Score: 3
[1102/6000] News | synthetic | 118948 | Score: 3
[1103/6000] News | original | 152083 | Score: 3
[1104/6000] News | synthetic | 152083 | Score: 3
[1105/6000] News | original | 45505 | Score: 3
[1106/6000] News | synthetic | 45505 | Score: 3
[1107/6000] News | original | 129409 | Score: 3
[1108/6000] News | synthetic | 129409 | Score: 3
[1109/6000] News | original | 6504 | Score: 3
[1110/6000] News | synthetic | 6504 | Score: 3
[1111/6000] News | original | 205832 | Score: 3
[1112/6000] News | synthetic | 205832 | Score: 3
[1113/6000] News | original | 93109 | Score: 3
[1114/6000] News | synthetic | 93109 | Score: 3
[1115/6000] News | original | 60225 | Score: 3
[1116/6000] News | synthetic | 60225 | Score: 1
[1117/6000] News | original | 151332 | Score: 3
[1118/6000] News | synthetic | 151332 | Score: 3
[1119/6000] News | original | 101733 | Score: 3
[1120/6000] News | synthetic | 101733 | Score: 3
[1121/6000] News | original | 237625 | Score: 3
[1122/6000] News | synthetic | 237625 | Score: 3
[1123/6000] News | original | 187834 | Score: 3
[1124/6000] News | synthetic | 187834 | Score: 3
[1125/6000] News | original | 57903 | Score: 3
[1126/6000] News | synthetic | 57903 | Score: 3
[1127/6000] News | original | 59025 | Score: 3
[1128/6000] News | synthetic | 59025 | Score: 3
[1129/6000] News | original | 13830 | Score: 3
[1130/6000] News | synthetic | 13830 | Score: 3
[1131/6000] News | original | 65407 | Score: 3
[1132/6000] News | synthetic | 65407 | Score: 3
[1133/6000] News | original | 183602 | Score: 3
[1134/6000] News | synthetic | 183602 | Score: 3
[1135/6000] News | original | 105552 | Score: 3
[1136/6000] News | synthetic | 105552 | Score: 3
[1137/6000] News | original | 90094 | Score: 3
[1138/6000] News | synthetic | 90094 | Score: 3
[1139/6000] News | original | 86417 | Score: 3
[1140/6000] News | synthetic | 86417 | Score: 3
[1141/6000] News | original | 174598 | Score: 3
[1142/6000] News | synthetic | 174598 | Score: 3
[1143/6000] News | original | 8282 | Score: 3
[1144/6000] News | synthetic | 8282 | Score: 3
[1145/6000] News | original | 179812 | Score: 3
[1146/6000] News | synthetic | 179812 | Score: 3
[1147/6000] News | original | 43781 | Score: 3
[1148/6000] News | synthetic | 43781 | Score: 3
[1149/6000] News | original | 105338 | Score: 3
[1150/6000] News | synthetic | 105338 | Score: 3
[1151/6000] News | original | 253844 | Score: 2
[1152/6000] News | synthetic | 253844 | Score: 3
[1153/6000] News | original | 152684 | Score: 3
[1154/6000] News | synthetic | 152684 | Score: 2
[1155/6000] News | original | 6300 | Score: 3
[1156/6000] News | synthetic | 6300 | Score: 3
[1157/6000] News | original | 15399 | Score: 3
[1158/6000] News | synthetic | 15399 | Score: 3
[1159/6000] News | original | 86138 | Score: 3
[1160/6000] News | synthetic | 86138 | Score: 3
[1161/6000] News | original | 253867 | Score: 3
[1162/6000] News | synthetic | 253867 | Score: 3
[1163/6000] News | original | 77015 | Score: 3
[1164/6000] News | synthetic | 77015 | Score: 3
[1165/6000] News | original | 49399 | Score: 3
[1166/6000] News | synthetic | 49399 | Score: 3
[1167/6000] News | original | 190070 | Score: 3
[1168/6000] News | synthetic | 190070 | Score: 3
[1169/6000] News | original | 203138 | Score: 3
[1170/6000] News | synthetic | 203138 | Score: 2
[1171/6000] News | original | 136084 | Score: 3
[1172/6000] News | synthetic | 136084 | Score: 3
[1173/6000] News | original | 168127 | Score: 3
[1174/6000] News | synthetic | 168127 | Score: 3
[1175/6000] News | original | 92905 | Score: 3
[1176/6000] News | synthetic | 92905 | Score: 1
[1177/6000] News | original | 36038 | Score: 3
[1178/6000] News | synthetic | 36038 | Score: 3
[1179/6000] News | original | 66126 | Score: 3
[1180/6000] News | synthetic | 66126 | Score: 3
[1181/6000] News | original | 236678 | Score: 3
[1182/6000] News | synthetic | 236678 | Score: 0
[1183/6000] News | original | 6912 | Score: 3
[1184/6000] News | synthetic | 6912 | Score: 3
[1185/6000] News | original | 71224 | Score: 3
[1186/6000] News | synthetic | 71224 | Score: 3
[1187/6000] News | original | 219188 | Score: 3
[1188/6000] News | synthetic | 219188 | Score: 3
[1189/6000] News | original | 219018 | Score: 3
[1190/6000] News | synthetic | 219018 | Score: 3
[1191/6000] News | original | 173176 | Score: 3
[1192/6000] News | synthetic | 173176 | Score: 3
[1193/6000] News | original | 227459 | Score: 3
[1194/6000] News | synthetic | 227459 | Score: 3
[1195/6000] News | original | 32081 | Score: 3
[1196/6000] News | synthetic | 32081 | Score: 3
[1197/6000] News | original | 45067 | Score: 3
[1198/6000] News | synthetic | 45067 | Score: 3
[1199/6000] News | original | 82425 | Score: 3
[1200/6000] News | synthetic | 82425 | Score: 3
[1201/6000] News | original | 61996 | Score: 3
[1202/6000] News | synthetic | 61996 | Score: 3
[1203/6000] News | original | 226089 | Score: 3
[1204/6000] News | synthetic | 226089 | Score: 3
[1205/6000] News | original | 230575 | Score: 3
[1206/6000] News | synthetic | 230575 | Score: 3
[1207/6000] News | original | 50727 | Score: 3
[1208/6000] News | synthetic | 50727 | Score: 3
[1209/6000] News | original | 6010 | Score: 3
[1210/6000] News | synthetic | 6010 | Score: 3
[1211/6000] News | original | 212313 | Score: 3
[1212/6000] News | synthetic | 212313 | Score: 3
[1213/6000] News | original | 141477 | Score: 3
[1214/6000] News | synthetic | 141477 | Score: 3
[1215/6000] News | original | 145607 | Score: 3
[1216/6000] News | synthetic | 145607 | Score: 2
[1217/6000] News | original | 113417 | Score: 3
[1218/6000] News | synthetic | 113417 | Score: 3
[1219/6000] News | original | 212024 | Score: 3
[1220/6000] News | synthetic | 212024 | Score: 3
[1221/6000] News | original | 100780 | Score: 3
[1222/6000] News | synthetic | 100780 | Score: 3
[1223/6000] News | original | 149304 | Score: 3
[1224/6000] News | synthetic | 149304 | Score: 3
[1225/6000] News | original | 209135 | Score: 3
[1226/6000] News | synthetic | 209135 | Score: 3
[1227/6000] News | original | 224425 | Score: 3
[1228/6000] News | synthetic | 224425 | Score: 3
[1229/6000] News | original | 216300 | Score: 3
[1230/6000] News | synthetic | 216300 | Score: 3
[1231/6000] News | original | 26662 | Score: 3
[1232/6000] News | synthetic | 26662 | Score: 3
[1233/6000] News | original | 33364 | Score: 3
[1234/6000] News | synthetic | 33364 | Score: 3
[1235/6000] News | original | 185925 | Score: 3
[1236/6000] News | synthetic | 185925 | Score: 3
[1237/6000] News | original | 167609 | Score: 3
[1238/6000] News | synthetic | 167609 | Score: 3
[1239/6000] News | original | 212207 | Score: 3
[1240/6000] News | synthetic | 212207 | Score: 3
[1241/6000] News | original | 51579 | Score: 3
[1242/6000] News | synthetic | 51579 | Score: 3
[1243/6000] News | original | 123201 | Score: 3
[1244/6000] News | synthetic | 123201 | Score: 3
[1245/6000] News | original | 119806 | Score: 3
[1246/6000] News | synthetic | 119806 | Score: 3
[1247/6000] News | original | 88944 | Score: 3
[1248/6000] News | synthetic | 88944 | Score: 3
[1249/6000] News | original | 106828 | Score: 3
[1250/6000] News | synthetic | 106828 | Score: 3
[1251/6000] News | original | 38131 | Score: 3
[1252/6000] News | synthetic | 38131 | Score: 3
[1253/6000] News | original | 92509 | Score: 3
[1254/6000] News | synthetic | 92509 | Score: 3
[1255/6000] News | original | 191115 | Score: 3
[1256/6000] News | synthetic | 191115 | Score: 3
[1257/6000] News | original | 11063 | Score: 3
[1258/6000] News | synthetic | 11063 | Score: 3
[1259/6000] News | original | 252533 | Score: 3
[1260/6000] News | synthetic | 252533 | Score: 3
[1261/6000] News | original | 153268 | Score: 3
[1262/6000] News | synthetic | 153268 | Score: 3
[1263/6000] News | original | 139680 | Score: 3
[1264/6000] News | synthetic | 139680 | Score: 2
[1265/6000] News | original | 8659 | Score: 3
[1266/6000] News | synthetic | 8659 | Score: 3
[1267/6000] News | original | 169281 | Score: 3
[1268/6000] News | synthetic | 169281 | Score: 3
[1269/6000] News | original | 198132 | Score: 3
[1270/6000] News | synthetic | 198132 | Score: 3
[1271/6000] News | original | 145970 | Score: 3
[1272/6000] News | synthetic | 145970 | Score: 3
[1273/6000] News | original | 57081 | Score: 3
[1274/6000] News | synthetic | 57081 | Score: 3
[1275/6000] News | original | 113572 | Score: 3
[1276/6000] News | synthetic | 113572 | Score: 3
[1277/6000] News | original | 68879 | Score: 3
[1278/6000] News | synthetic | 68879 | Score: 3
[1279/6000] News | original | 139698 | Score: 3
[1280/6000] News | synthetic | 139698 | Score: 3
[1281/6000] News | original | 158537 | Score: 3
[1282/6000] News | synthetic | 158537 | Score: 3
[1283/6000] News | original | 41280 | Score: 3
[1284/6000] News | synthetic | 41280 | Score: 3
[1285/6000] News | original | 130168 | Score: 3
[1286/6000] News | synthetic | 130168 | Score: 3
[1287/6000] News | original | 50188 | Score: 3
[1288/6000] News | synthetic | 50188 | Score: 3
[1289/6000] News | original | 238545 | Score: 3
[1290/6000] News | synthetic | 238545 | Score: 3
[1291/6000] News | original | 203480 | Score: 3
[1292/6000] News | synthetic | 203480 | Score: 3
[1293/6000] News | original | 43792 | Score: 3
[1294/6000] News | synthetic | 43792 | Score: 3
[1295/6000] News | original | 106266 | Score: 3
[1296/6000] News | synthetic | 106266 | Score: 3
[1297/6000] News | original | 58762 | Score: 3
[1298/6000] News | synthetic | 58762 | Score: 2
[1299/6000] News | original | 50897 | Score: 3
[1300/6000] News | synthetic | 50897 | Score: 3
[1301/6000] News | original | 219593 | Score: 3
[1302/6000] News | synthetic | 219593 | Score: 3
[1303/6000] News | original | 199750 | Score: 3
[1304/6000] News | synthetic | 199750 | Score: 3
[1305/6000] News | original | 230073 | Score: 3
[1306/6000] News | synthetic | 230073 | Score: 2
[1307/6000] News | original | 82466 | Score: 3
[1308/6000] News | synthetic | 82466 | Score: 3
[1309/6000] News | original | 133633 | Score: 3
[1310/6000] News | synthetic | 133633 | Score: 3
[1311/6000] News | original | 142922 | Score: 3
[1312/6000] News | synthetic | 142922 | Score: 3
[1313/6000] News | original | 101757 | Score: 3
[1314/6000] News | synthetic | 101757 | Score: 3
[1315/6000] News | original | 132803 | Score: 3
[1316/6000] News | synthetic | 132803 | Score: 3
[1317/6000] News | original | 69223 | Score: 3
[1318/6000] News | synthetic | 69223 | Score: 3
[1319/6000] News | original | 242535 | Score: 3
[1320/6000] News | synthetic | 242535 | Score: 2
[1321/6000] News | original | 39978 | Score: 3
[1322/6000] News | synthetic | 39978 | Score: 3
[1323/6000] News | original | 209071 | Score: 3
[1324/6000] News | synthetic | 209071 | Score: 3
[1325/6000] News | original | 228882 | Score: 3
[1326/6000] News | synthetic | 228882 | Score: 3
[1327/6000] News | original | 158386 | Score: 3
[1328/6000] News | synthetic | 158386 | Score: 3
[1329/6000] News | original | 92065 | Score: 3
[1330/6000] News | synthetic | 92065 | Score: 3
[1331/6000] News | original | 245887 | Score: 3
[1332/6000] News | synthetic | 245887 | Score: 3
[1333/6000] News | original | 88317 | Score: 3
[1334/6000] News | synthetic | 88317 | Score: 3
[1335/6000] News | original | 173579 | Score: 3
[1336/6000] News | synthetic | 173579 | Score: 3
[1337/6000] News | original | 204990 | Score: 3
[1338/6000] News | synthetic | 204990 | Score: 3
[1339/6000] News | original | 119526 | Score: 3
[1340/6000] News | synthetic | 119526 | Score: 3
[1341/6000] News | original | 238971 | Score: 3
[1342/6000] News | synthetic | 238971 | Score: 3
[1343/6000] News | original | 62404 | Score: 3
[1344/6000] News | synthetic | 62404 | Score: 3
[1345/6000] News | original | 162650 | Score: 3
[1346/6000] News | synthetic | 162650 | Score: 3
[1347/6000] News | original | 109154 | Score: 3
[1348/6000] News | synthetic | 109154 | Score: 3
[1349/6000] News | original | 227342 | Score: 3
[1350/6000] News | synthetic | 227342 | Score: 3
[1351/6000] News | original | 181364 | Score: 3
[1352/6000] News | synthetic | 181364 | Score: 3
[1353/6000] News | original | 45982 | Score: 3
[1354/6000] News | synthetic | 45982 | Score: 3
[1355/6000] News | original | 212675 | Score: 3
[1356/6000] News | synthetic | 212675 | Score: 1
[1357/6000] News | original | 169216 | Score: 2
[1358/6000] News | synthetic | 169216 | Score: 3
[1359/6000] News | original | 143845 | Score: 3
[1360/6000] News | synthetic | 143845 | Score: 3
[1361/6000] News | original | 143425 | Score: 3
[1362/6000] News | synthetic | 143425 | Score: 3
[1363/6000] News | original | 133316 | Score: 3
[1364/6000] News | synthetic | 133316 | Score: 3
[1365/6000] News | original | 104836 | Score: 3
[1366/6000] News | synthetic | 104836 | Score: 3
[1367/6000] News | original | 251336 | Score: 3
[1368/6000] News | synthetic | 251336 | Score: 3
[1369/6000] News | original | 203701 | Score: 3
[1370/6000] News | synthetic | 203701 | Score: 1
[1371/6000] News | original | 250494 | Score: 3
[1372/6000] News | synthetic | 250494 | Score: 3
[1373/6000] News | original | 24468 | Score: 3
[1374/6000] News | synthetic | 24468 | Score: 3
[1375/6000] News | original | 238502 | Score: 3
[1376/6000] News | synthetic | 238502 | Score: 3
[1377/6000] News | original | 168529 | Score: 3
[1378/6000] News | synthetic | 168529 | Score: 3
[1379/6000] News | original | 123486 | Score: 3
[1380/6000] News | synthetic | 123486 | Score: 3
[1381/6000] News | original | 106987 | Score: 3
[1382/6000] News | synthetic | 106987 | Score: 3
[1383/6000] News | original | 52318 | Score: 3
[1384/6000] News | synthetic | 52318 | Score: 3
[1385/6000] News | original | 119481 | Score: 3
[1386/6000] News | synthetic | 119481 | Score: 3
[1387/6000] News | original | 133017 | Score: 3
[1388/6000] News | synthetic | 133017 | Score: 3
[1389/6000] News | original | 70043 | Score: 3
[1390/6000] News | synthetic | 70043 | Score: 3
[1391/6000] News | original | 192898 | Score: 3
[1392/6000] News | synthetic | 192898 | Score: 3
[1393/6000] News | original | 78884 | Score: 3
[1394/6000] News | synthetic | 78884 | Score: 3
[1395/6000] News | original | 44615 | Score: 3
[1396/6000] News | synthetic | 44615 | Score: 3
[1397/6000] News | original | 104745 | Score: 3
[1398/6000] News | synthetic | 104745 | Score: 3
[1399/6000] News | original | 136409 | Score: 3
[1400/6000] News | synthetic | 136409 | Score: 3
[1401/6000] News | original | 95069 | Score: 3
[1402/6000] News | synthetic | 95069 | Score: 3
[1403/6000] News | original | 198313 | Score: 3
[1404/6000] News | synthetic | 198313 | Score: 3
[1405/6000] News | original | 207263 | Score: 3
[1406/6000] News | synthetic | 207263 | Score: 3
[1407/6000] News | original | 193838 | Score: 3
[1408/6000] News | synthetic | 193838 | Score: 3
[1409/6000] News | original | 226725 | Score: 3
[1410/6000] News | synthetic | 226725 | Score: 3
[1411/6000] News | original | 85302 | Score: 3
[1412/6000] News | synthetic | 85302 | Score: 3
[1413/6000] News | original | 28785 | Score: 3
[1414/6000] News | synthetic | 28785 | Score: 3

## Export final labels

In [ ]:
 relevance_df = pd.read_csv("/content/drive/MyDrive/relevance_labels_checkpoint.csv")

print(relevance_df.shape)
print(relevance_df["query_type"].value_counts())
print(relevance_df["dataset"].value_counts())
print(relevance_df["relevance_score"].value_counts().sort_index())

(6000, 8)
query_type
original     3000
synthetic    3000
Name: count, dtype: int64
dataset
News         2000
Tenders      2000
Abstracts    2000
Name: count, dtype: int64
relevance_score
0      48
1     735
2     752
3    4465
Name: count, dtype: int64

In [ ]:
relevance_summary = (
    relevance_df
    .groupby(["dataset", "query_type"])["relevance_score"]
    .agg(["count", "mean", "median", "std"])
    .round(3)
)

display(relevance_summary)

                      count   mean  median    std
dataset   query_type
Abstracts original     1000  2.449     3.0  0.836
          synthetic    1000  2.344     3.0  0.816
News      original     1000  2.984     3.0  0.133
          synthetic    1000  2.905     3.0  0.355
Tenders   original     1000  2.466     3.0  0.844
          synthetic    1000  2.486     3.0  0.784

In [ ]:
relevance_distribution = (
    relevance_df
    .groupby(["dataset", "query_type", "relevance_score"])
    .size()
    .unstack(fill_value=0)
)

display(relevance_distribution)

relevance_score        0    1    2    3
dataset   query_type
Abstracts original    18  171  155  656
          synthetic    1  217  219  563
News      original     0    1   14  985
          synthetic    2   14   61  923
Tenders   original    26  153  150  671
          synthetic    1  179  153  667

In [ ]:
relevance_distribution_pct = (
    relevance_df
    .groupby(["dataset", "query_type"])["relevance_score"]
    .value_counts(normalize=True)
    .unstack(fill_value=0)
    .mul(100)
    .round(1)
)

display(relevance_distribution_pct)

relevance_score         0     1     2     3
dataset   query_type
Abstracts original    1.8  17.1  15.5  65.6
          synthetic   0.1  21.7  21.9  56.3
News      original    0.0   0.1   1.4  98.5
          synthetic   0.2   1.4   6.1  92.3
Tenders   original    2.6  15.3  15.0  67.1
          synthetic   0.1  17.9  15.3  66.7

In [ ]:
paired = relevance_df.pivot(
    index=["dataset", "query_id"],
    columns="query_type",
    values="relevance_score"
).reset_index()

paired["difference"] = (
    paired["synthetic"] - paired["original"]
)

display(
    paired.groupby("dataset")["difference"]
    .value_counts()
    .unstack(fill_value=0)
)

difference  -3   -2   -1    0    1   2   3
dataset
Abstracts    1  101  175  531  117  67   8
News         2   14   61  908   14   1   0
Tenders      0  101  121  540  141  89   8

In [ ]:
paired_summary = (
    paired
    .groupby("dataset")["difference"]
    .agg(
        mean="mean",
        median="median",
        std="std",
        lower=lambda x: (x < 0).sum(),
        equal=lambda x: (x == 0).sum(),
        higher=lambda x: (x > 0).sum()
    )
    .round(3)
)

display(paired_summary)

            mean  median    std  lower  equal  higher
dataset
Abstracts -0.105     0.0  1.017    277    531     192
News      -0.079     0.0  0.383     77    908      15
Tenders    0.020     0.0  1.046    222    540     238

In [ ]:
from scipy.stats import wilcoxon

for dataset in paired["dataset"].unique():
    subset = paired[paired["dataset"] == dataset]

    stat, p = wilcoxon(
        subset["original"],
        subset["synthetic"]
    )

    print(
        dataset,
        f"W = {stat:.1f}, p = {p:.4g}"
    )

Abstracts W = 46086.0, p = 0.001432
News W = 615.0, p = 1.794e-10
Tenders W = 52019.0, p = 0.7182

In [ ]:
stat, p = wilcoxon(
    paired["original"],
    paired["synthetic"]
)

print(f"Overall: W = {stat:.1f}, p = {p:.4g}")

Overall: W = 229984.0, p = 0.000677